# Diabetes Prediction Using Linear Regression and Gradient Descent

## Project Overview

This project explores linear regression for predicting a continuous target variable using the Diabetes dataset. Three approaches are implemented and compared:

1. **Linear Regression:** A closed-form optimization approach provided by scikit-learn.
2. **SGDRegressor:** A gradient-based optimization algorithm provided by scikit-learn.
3. **Gradient Descent from Scratch:** A custom implementation using NumPy.

The models are evaluated using Mean Squared Error (MSE) and the coefficient of determination (\(R^2\)).

### Objectives

- Understand the workflow of a regression problem.
- Prepare features and target variables.
- Split the dataset into training and testing sets.
- Understand the importance of feature scaling.
- Implement gradient descent for multiple linear regression.
- Compare the predictive performance of different approaches.

## 2. Initial Data Exploration

Before building the models, we inspect the dataset to understand its structure and identify potential data-quality issues.

The initial exploration includes:

- Viewing sample rows.
- Checking the number of rows and columns.
- Inspecting column names and data types.
- Checking for missing values.
- Examining descriptive statistics.

In [30]:
import pandas as pd
import numpy as np

In [31]:
df=pd.read_csv(r'C:\Users\Niloy\Downloads\ml practice\Diabetes.csv')

In [32]:
df

     BMI   BP  Cholesterol  LDL  Target
0     26   99          165   75     524
1     39   65          285   92     717
2     34   70          226   77     655
3     31  114          274   63     732
4     21   96          198   68     606
..   ...  ...          ...  ...     ...
195   26  116          221  181     784
196   34  112          250  190     902
197   38   86          176  135     703
198   38  105          179  154     747
199   35  105          156  188     804

[200 rows x 5 columns]

## 3. Feature Selection and Train-Test Split

The independent variables (features) are stored in `X`, while the dependent variable (target) is stored in `y`.

The `Target` column is removed from the feature matrix because it is the value the models are expected to predict.

The dataset is divided into:

- **Training set (80%):** Used to train the models.
- **Testing set (20%):** Used to evaluate their performance on unseen data.

A fixed `random_state` is used to make the split reproducible.

In [33]:
from sklearn.model_selection import train_test_split

In [34]:
X=df.drop('Target',axis=1)
y=df["Target"]

In [35]:
X

     BMI   BP  Cholesterol  LDL
0     26   99          165   75
1     39   65          285   92
2     34   70          226   77
3     31  114          274   63
4     21   96          198   68
..   ...  ...          ...  ...
195   26  116          221  181
196   34  112          250  190
197   38   86          176  135
198   38  105          179  154
199   35  105          156  188

[200 rows x 4 columns]

In [36]:
y

0      524
1      717
2      655
3      732
4      606
      ...
195    784
196    902
197    703
198    747
199    804
Name: Target, Length: 200, dtype: int64

In [37]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

## 4. Model 1: Linear Regression

Linear Regression models the relationship between the input features and the target variable as a linear function.

For multiple features, the prediction is calculated as:

$$
\hat{y} = b + w_1x_1 + w_2x_2 + \cdots + w_nx_n
$$

where:

- $\hat{y}$ is the predicted target.
- $b$ is the intercept (bias).
- $w_i$ is the coefficient associated with feature $i$.
- $x_i$ is the value of feature $i$.
- $n$ is the total number of features.

The scikit-learn `LinearRegression` model is trained on the training data and used to generate predictions for the test set.

The intercept and coefficients are examined to understand the fitted model.

In [38]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()

In [39]:
lr.fit(X_train,y_train)

LinearRegression()

In [40]:
y_pred = lr.predict(X_test)

In [41]:
y_pred

array([705.39129263, 761.25918522, 720.20094621, 865.45330098,
       505.16813913, 764.64987995, 743.48772082, 583.10281085,
       819.5413881 , 928.13274205, 589.24372257, 670.51430514,
       744.59304568, 913.65219667, 649.81193439, 792.91195041,
       565.42048475, 733.96973962, 587.19201343, 534.66650148,
       798.73965973, 524.98973887, 772.74213134, 569.27166927,
       608.08741575, 597.49710354, 823.14874525, 712.83187191,
       795.8777001 , 774.25758947, 666.83659114, 820.83360095,
       631.10084116, 929.0456283 , 630.36252255, 664.15744308,
       833.99361221, 763.50213565, 560.45857963, 562.63530813])

### 4.1 Model Evaluation

Two metrics are used to evaluate the regression model.

**Mean Squared Error (MSE)**

MSE measures the average squared difference between actual and predicted values.

$$
\mathrm{MSE} = \frac{1}{m}\sum_{i=1}^{m}(y_i - \hat{y}_i)^2
$$

A lower MSE generally indicates smaller prediction errors.

**Coefficient of Determination ($(R^2)$)**

The $(R^2)$ score measures how much of the variation in the target variable is explained by the model.

$$
R^2 = 1 - \frac{\sum_{i=1}^{m}(y_i - \hat{y}_i)^2}{\sum_{i=1}^{m}(y_i - \bar{y})^2}
$$

A score closer to 1 generally indicates a better fit. However, model performance should be judged using appropriate metrics and validation, not $(R^2)$ alone.

In [42]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
print("MSE:",mean_squared_error(y_test,y_pred))
print("R2:",r2_score(y_test,y_pred))

MSE: 744.095990475563
R2: 0.9478149183108617

In [43]:
print("Intercept:", lr.intercept_)
print("Coefficients:", lr.coef_)

Intercept: 18.472338888135937
Coefficients: [2.78757413 1.26585164 1.20012758 1.74127399]

## 5. Feature Scaling

Gradient-based optimization algorithms can be sensitive to differences in feature magnitudes. Standardization transforms each feature to have approximately zero mean and unit standard deviation.

The transformation is:

$$
z=\frac{x-\mu}{\sigma}
$$

where \($mu$) is the mean and \($sigma$) is the standard deviation calculated from the training data.

The scaler is fitted **only on the training set** and then applied to both the training and testing sets. This prevents information from the test set from leaking into the training process.

Feature scaling is used for `SGDRegressor` and the custom gradient descent model.

In [44]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

X_trained_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

## 6. Model 2: SGDRegressor

`SGDRegressor` is a scikit-learn implementation of linear regression trained using Stochastic Gradient Descent (SGD).

Unlike standard Linear Regression, which computes a least-squares solution directly, SGD updates the model parameters iteratively using gradients.

The learning rate controls the size of each parameter update. In this implementation, `learning_rate="constant"` keeps the learning rate fixed at the value specified by `eta0`.

After training, predictions are generated for the scaled test data. The model's intercept, coefficients, MSE, and $(R^2)$ score are examined.

In [45]:
from sklearn.linear_model import SGDRegressor
model = SGDRegressor(learning_rate='constant',eta0=0.01,max_iter=1000,random_state=42)
model.fit(X_trained_scaled,y_train)

SGDRegressor(learning_rate='constant', random_state=42)

In [46]:
y_pred_gd = model.predict(X_test_scaled)

In [47]:
y_pred_gd

array([704.79034814, 758.02478576, 722.1733962 , 866.12343924,
       501.29802696, 767.8300578 , 742.40313308, 579.64398155,
       816.58076321, 930.59566814, 587.45494975, 671.55193623,
       744.23280781, 913.41363743, 649.5767931 , 788.38323174,
       565.25404968, 732.38256233, 583.97565102, 530.65323595,
       798.76028701, 521.46368364, 769.56171391, 567.46570922,
       608.04092843, 596.87440738, 822.43605768, 713.17672805,
       796.45305554, 768.30575274, 665.68341961, 820.77917111,
       631.39254296, 929.24902585, 630.3086873 , 665.16349169,
       829.44458027, 765.3471217 , 559.34030168, 564.32713849])

In [48]:
print("Intercept:", model.intercept_)
print("Coefficients:", model.coef_)

Intercept: [695.4260951]
Coefficients: [19.50347639 24.28647011 54.49543865 69.54836658]

In [49]:
df

     BMI   BP  Cholesterol  LDL  Target
0     26   99          165   75     524
1     39   65          285   92     717
2     34   70          226   77     655
3     31  114          274   63     732
4     21   96          198   68     606
..   ...  ...          ...  ...     ...
195   26  116          221  181     784
196   34  112          250  190     902
197   38   86          176  135     703
198   38  105          179  154     747
199   35  105          156  188     804

[200 rows x 5 columns]

In [50]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
print("MSE:",mean_squared_error(y_test,y_pred_gd))
print("R2:",r2_score(y_test,y_pred_gd))

MSE: 743.1871085793949
R2: 0.9478786601890662

In [51]:
df["Target"].mean()

np.float64(699.73)

## 7. Model 3: Gradient Descent from Scratch

In this section, multiple linear regression is implemented using NumPy without relying on a prebuilt regression estimator.

### Prediction equation

$$
\hat{y} = Xw + b
$$

Here, \(X\) represents the feature matrix, \(w\) represents the vector of weights, and \(b\) represents the bias.

### Cost function

The algorithm minimizes the following cost function:

$$
J(w,b)=\frac{1}{2m}\sum_{i=1}^{m}(\hat{y}_i-y_i)^2
$$

### Gradients

The gradients of the cost function with respect to the weights and bias are:

$$
dw=\frac{1}{m}X^T(\hat{y}-y)
$$

$$
db=\frac{1}{m}\sum_{i=1}^{m}(\hat{y}_i-y_i)
$$

### Parameter updates

The weights and bias are updated iteratively:

$$
w:=w-\alpha dw
$$

$$
b:=b-\alpha db
$$

where \($alpha$) is the learning rate.

This implementation uses **Batch Gradient Descent**, because each update uses the full training dataset. The number of epochs and learning rate control the training process.

Finally, the trained model predicts target values for the test set, and its learned weights and bias are inspected.

In [52]:
import numpy as np
class Gradient_descent:
    def __init__(self,epoch,learning_rate):
        self.epoch = epoch
        self.learning_rate = learning_rate
        self.weight=None
        self.bias=None
    def fit(self,X_train,y_train):
        self.weight=np.zeros(X_train.shape[1])
        self.bias = 0
        for i in range(self.epoch):
            y_pred = np.dot(X_train,self.weight )+ self.bias
            error=y_pred-y_train
            
            dw=np.dot(X_train.T,error)/len(X_train)
            db=np.mean(error)

            self.weight-=self.learning_rate*dw
            self.bias-=self.learning_rate*db
    def predict(self,X_test):
        return np.dot(X_test,self.weight)+self.bias
    def co_efficient(self):
        return self.weight
    def intercept(self):
        return self.bias

In [53]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train_sc = sc.fit_transform(X_train)
X_test_sc = sc.transform(X_test)

In [54]:
GD= Gradient_descent(1000,0.01)

In [55]:
GD.fit(X_train_sc,y_train)

In [56]:
y_pred_GD=GD.predict(X_test_sc)

In [57]:
y_pred_GD

array([705.3632843 , 761.23444863, 720.1722293 , 865.41361453,
       505.15918979, 764.61868289, 743.44391098, 583.07748006,
       819.50343772, 928.08179244, 589.22399211, 670.47879272,
       744.55687673, 913.60763829, 649.78800417, 792.87728936,
       565.40454924, 733.94115362, 587.16995097, 534.65300161,
       798.70069871, 524.9727523 , 772.71652544, 569.25157777,
       608.05992705, 597.47682382, 823.11490054, 712.78962021,
       795.84420656, 774.22613119, 666.81396904, 820.79606686,
       631.06736453, 928.99697012, 630.329069  , 664.11821122,
       833.95831758, 763.46989069, 560.43738415, 562.61054466])

In [58]:
print(GD.co_efficient())
print(GD.intercept())

[18.16364354 22.52139353 54.89242728 69.0226249 ]
696.6949215126479